In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import pandas as pd

In [2]:
pokemon_df = pd.read_csv('data/pokemon_df.csv')

In [3]:
pokemon_df

,Winner_mark,HP_first,Attack_first,Defense_first,Sp. Atk_first,Sp. Def_first,Speed_first,HP_second,Attack_second,Defense_second,...,Generation_second_1,Generation_second_2,Generation_second_3,Generation_second_4,Generation_second_5,Generation_second_6,Legendary_first_0,Legendary_first_1,Legendary_second_0,Legendary_second_1
0,2,50,64,50,45,50,41,70,70,40,...,0,0,1,0,0,0,1,0,1,0
1,2,91,90,72,90,129,108,91,129,90,...,0,0,0,0,1,0,0,1,0,1
2,2,55,40,85,80,105,40,75,75,75,...,0,0,0,0,1,0,1,0,1,0
3,2,40,40,40,70,40,20,77,120,90,...,0,0,0,0,1,0,1,0,1,0
4,1,70,60,125,115,70,55,20,10,230,...,0,1,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1,100,120,100,150,120,90,30,40,70,...,1,0,0,0,0,0,0,1,1,0
49996,1,60,85,40,30,45,68,35,55,40,...,0,0,0,0,1,0,1,0,1,0
49997,2,60,50,100,85,70,65,73,115,60,...,0,0,1,0,0,0,1,0,1,0
49998,1,40,30,50,55,55,100,25,35,70,...,1,0,0,0,0,0,1,0,1,0
49999,1,78,104,78,159,115,100,70,80,50,...,1,0,0,0,0,0,1,0,1,0

In [5]:
X = pokemon_df.drop('Winner_mark',axis=1)
y = pokemon_df['Winner_mark']

In [6]:
# Train/Test(val) 분리
X_train,X_test, y_train,y_test = train_test_split(X,y,stratify=y,random_state=1)

In [7]:
tree = DecisionTreeClassifier(random_state=1)
tree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=1)

In [8]:
pred_train = tree.predict(X_train)
pred_test = tree.predict(X_test)

In [9]:
accuracy_score(y_train,pred_train),accuracy_score(y_test,pred_test)

(0.99992, 0.92264)

In [10]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,pred_train)

array([[17701,     0],
       [    3, 19796]], dtype=int64)

In [11]:
print(classification_report(y_test,pred_test))

              precision    recall  f1-score   support

           1       0.92      0.92      0.92      5900
           2       0.93      0.93      0.93      6600

    accuracy                           0.92     12500
   macro avg       0.92      0.92      0.92     12500
weighted avg       0.92      0.92      0.92     12500